"""
Traffic Congestion Analysis
Author: Ishita Parnami 
Date: 21 November 2025
Big Data Project - Jk Lakshmipat University
"""

# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18l-ij76ismEH6dV6ZqJNDEE5hnTHrs7_
"""

# ps-2-graph.py - Updated for Google Colab
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import glob
import os

print("📊 Creating Accident Impact Visualizations...")

try:
    # Read from CSV instead of Parquet
    df = pd.read_csv("accident_alerts.csv")

    print("Accident Alerts Data:")
    print(df.head())
    print(f"Total alerts: {len(df)}")

    if len(df) == 0:
        print("No high impact accident alerts found")
        # Try to load the windowed analysis for context
        try:
            df_analysis = pd.read_csv("windowed_traffic_analysis.csv")
            print("Showing general traffic analysis instead:")
            create_general_analysis(df_analysis)
        except:
            print("No data available for visualization")
    else:
        create_alert_visualizations(df)

except FileNotFoundError:
    print("❌ accident_alerts.csv not found. Please run ps-2.py first")
except Exception as e:
    print(f"❌ Error: {e}")

def create_alert_visualizations(df):
    """Create comprehensive visualizations for accident alerts"""

    # Clean and prepare data
    if 'window' in df.columns and isinstance(df['window'].iloc[0], str):
        import ast
        df['window_dict'] = df['window'].apply(ast.literal_eval)
        df['window_start'] = df['window_dict'].apply(lambda x: x['start'])
        df['window_end'] = df['window_dict'].apply(lambda x: x['end'])

    # Visualization 1: Main Alert Bar Chart
    fig1 = px.bar(
        df,
        x="road_id",
        y="avg_current_speed",
        color="severity",
        hover_data=["vehicle_count", "window_start", "window_end"],
        title="🚨 Average Speed per Road during High Impact Accidents",
        labels={
            "avg_current_speed": "Average Speed (km/h)",
            "road_id": "Road ID",
            "severity": "Accident Severity"
        },
        color_discrete_map={
            "High": "#D62728",
            "Medium": "#FF7F0E",
            "Low": "#2CA02C"
        }
    )

    # Add speed threshold line
    fig1.add_hline(y=8, line_dash="dash", line_color="red",
                  annotation_text="Speed Threshold (8 km/h)")

    fig1.update_layout(
        template="plotly_white",
        height=500,
        showlegend=True
    )
    fig1.show()

    # Visualization 2: Multi-metric Analysis
    fig2 = make_subplots(
        rows=2, cols=1,
        subplot_titles=('Average Speed vs Vehicle Count', 'Accident Impact Timeline'),
        vertical_spacing=0.15
    )

    # Subplot 1: Speed vs Vehicle Count
    for severity in df['severity'].unique():
        severity_data = df[df['severity'] == severity]
        fig2.add_trace(
            go.Scatter(
                x=severity_data['road_id'],
                y=severity_data['avg_current_speed'],
                mode='markers+text',
                name=f'{severity} Severity - Speed',
                text=severity_data['avg_current_speed'].round(1),
                textposition="top center",
                marker=dict(size=severity_data['vehicle_count']*3,
                           line=dict(width=2, color='DarkSlateGrey'))
            ),
            row=1, col=1
        )

    # Subplot 2: Timeline if available
    if 'window_start' in df.columns:
        df_sorted = df.sort_values('window_start')
        fig2.add_trace(
            go.Scatter(
                x=df_sorted['window_start'],
                y=df_sorted['avg_current_speed'],
                mode='lines+markers',
                name='Speed Trend',
                line=dict(color='red', width=3),
                marker=dict(size=8)
            ),
            row=2, col=1
        )

    fig2.update_layout(
        title_text="📈 Detailed Accident Impact Analysis",
        height=600,
        showlegend=True
    )
    fig2.update_yaxes(title_text="Average Speed (km/h)", row=1, col=1)
    fig2.update_xaxes(title_text="Road ID", row=1, col=1)
    if 'window_start' in df.columns:
        fig2.update_xaxes(title_text="Time Window", row=2, col=1)
        fig2.update_yaxes(title_text="Average Speed (km/h)", row=2, col=1)

    fig2.show()

    # Visualization 3: Impact Summary
    impact_summary = df.groupby('severity').agg({
        'road_id': 'count',
        'avg_current_speed': 'mean',
        'vehicle_count': 'mean'
    }).reset_index()

    fig3 = go.Figure()

    fig3.add_trace(go.Bar(
        x=impact_summary['severity'],
        y=impact_summary['road_id'],
        name='Number of Alerts',
        marker_color=['#D62728', '#FF7F0E', '#2CA02C']
    ))

    fig3.update_layout(
        title="🚦 Accident Alert Summary by Severity",
        xaxis_title="Accident Severity",
        yaxis_title="Number of High Impact Alerts",
        template="plotly_white",
        height=400
    )

    fig3.show()

    # Print summary statistics
    print("\n" + "="*50)
    print("📋 ACCIDENT IMPACT SUMMARY")
    print("="*50)
    print(f"Total High Impact Alerts: {len(df)}")
    print(f"Roads Affected: {df['road_id'].nunique()}")
    print(f"Average Speed Across Alerts: {df['avg_current_speed'].mean():.1f} km/h")
    print(f"Lowest Recorded Speed: {df['avg_current_speed'].min():.1f} km/h")
    print(f"Severity Distribution:")
    severity_counts = df['severity'].value_counts()
    for severity, count in severity_counts.items():
        print(f"  - {severity}: {count} alerts")

def create_general_analysis(df):
    """Create visualization for general traffic analysis when no alerts"""
    fig = px.bar(
        df,
        x="road_id",
        y="avg_current_speed",
        title="🚗 General Traffic Analysis (No High Impact Alerts)",
        labels={
            "avg_current_speed": "Average Speed (km/h)",
            "road_id": "Road ID"
        }
    )

    fig.add_hline(y=8, line_dash="dash", line_color="red",
                  annotation_text="Alert Threshold")

    fig.update_layout(
        template="plotly_white",
        height=500
    )
    fig.show()

print("✅ Visualization script ready!")

# =============================================================================
# ACCIDENT ALERT & TRAFFIC IMPACT VISUALIZATION DASHBOARD
# =============================================================================

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import numpy as np
from datetime import datetime, timedelta

print("🚨 Creating Accident Alert & Traffic Impact Dashboard...")

# =============================================================================
# SAMPLE DATA GENERATION (In case real data is not available)
# =============================================================================

def generate_sample_accident_data():
    """Generate sample accident and traffic data for demonstration"""

    # Sample accident data
    accidents_data = {
        'date': [
            '2025-11-21 08:30:00', '2025-11-21 09:15:00', '2025-11-21 10:45:00',
            '2025-11-21 11:20:00', '2025-11-21 12:05:00', '2025-11-21 13:40:00'
        ],
        'road_id': ['R001', 'R005', 'R009', 'R012', 'R015', 'R018'],
        'severity': ['High', 'Medium', 'Low', 'High', 'Medium', 'Low'],
        'cause': ['Collision', 'Breakdown', 'Minor', 'Multi-vehicle', 'Breakdown', 'Minor'],
        'fatalities': [1, 0, 0, 2, 0, 0]
    }

    # Sample traffic impact data (simulating windowed analysis)
    impact_data = []
    roads = ['R001', 'R005', 'R009', 'R012', 'R015', 'R018']
    severities = ['High', 'Medium', 'Low', 'High', 'Medium', 'Low']

    for i, road in enumerate(roads):
        base_time = datetime(2025, 11, 21, 8, 0)

        # Pre-accident normal traffic
        impact_data.append({
            'road_id': road,
            'window_start': base_time,
            'window_end': base_time + timedelta(minutes=10),
            'avg_current_speed': np.random.uniform(25, 40),
            'vehicle_count': np.random.randint(15, 25),
            'severity': severities[i],
            'High_Impact_Accident': False
        })

        # During accident (low speed)
        impact_data.append({
            'road_id': road,
            'window_start': base_time + timedelta(minutes=10),
            'window_end': base_time + timedelta(minutes=20),
            'avg_current_speed': np.random.uniform(3, 8),
            'vehicle_count': np.random.randint(1, 5),
            'severity': severities[i],
            'High_Impact_Accident': True
        })

        # Recovery phase
        impact_data.append({
            'road_id': road,
            'window_start': base_time + timedelta(minutes=20),
            'window_end': base_time + timedelta(minutes=30),
            'avg_current_speed': np.random.uniform(15, 25),
            'vehicle_count': np.random.randint(8, 15),
            'severity': severities[i],
            'High_Impact_Accident': False
        })

    return pd.DataFrame(accidents_data), pd.DataFrame(impact_data)

# =============================================================================
# LOAD OR GENERATE DATA
# =============================================================================

try:
    # Try to load real data
    accidents_df = pd.read_csv("accidents.txt")
    impact_df = pd.read_csv("accident_alerts.csv")
    print("✅ Loaded real data files")
except:
    # Generate sample data
    print("📋 Generating sample data for demonstration")
    accidents_df, impact_df = generate_sample_accident_data()
    print("Sample Accident Data:")
    print(accidents_df)
    print("\nSample Impact Data:")
    print(impact_df.head())

# =============================================================================
# VISUALIZATION 1: ACCIDENT SEVERITY OVERVIEW
# =============================================================================

print("🎨 Creating Visualization 1: Accident Severity Overview...")

fig1 = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'Accident Severity Distribution',
        'Accidents by Road',
        'Accident Causes',
        'Time of Day Analysis'
    ),
    specs=[
        [{"type": "pie"}, {"type": "bar"}],
        [{"type": "bar"}, {"type": "scatter"}]
    ],
    vertical_spacing=0.12,
    horizontal_spacing=0.08
)

# Subplot 1: Severity Distribution (Pie chart)
severity_counts = accidents_df['severity'].value_counts()
fig1.add_trace(
    go.Pie(
        labels=severity_counts.index,
        values=severity_counts.values,
        hole=0.4,
        marker_colors=['#DC3912', '#FF9900', '#109618'],
        name="Severity Distribution"
    ),
    row=1, col=1
)

# Subplot 2: Accidents by Road (Bar chart)
road_accidents = accidents_df['road_id'].value_counts().sort_index()
fig1.add_trace(
    go.Bar(
        x=road_accidents.index,
        y=road_accidents.values,
        marker_color='#3366CC',
        name="Accidents per Road"
    ),
    row=1, col=2
)

# Subplot 3: Accident Causes
cause_counts = accidents_df['cause'].value_counts()
fig1.add_trace(
    go.Bar(
        x=cause_counts.values,
        y=cause_counts.index,
        orientation='h',
        marker_color='#990099',
        name="Accident Causes"
    ),
    row=2, col=1
)

# Subplot 4: Time Analysis (if time data available)
if 'date' in accidents_df.columns:
    accidents_df['hour'] = pd.to_datetime(accidents_df['date']).dt.hour
    hourly_accidents = accidents_df.groupby('hour').size()
    fig1.add_trace(
        go.Scatter(
            x=hourly_accidents.index,
            y=hourly_accidents.values,
            mode='lines+markers',
            line=dict(color='#0099C6', width=3),
            marker=dict(size=8),
            name="Accidents by Hour"
        ),
        row=2, col=2
    )

fig1.update_layout(
    title_text="🚗 ACCIDENT ANALYSIS OVERVIEW",
    height=700,
    showlegend=False,
    template="plotly_white"
)

fig1.show()

# =============================================================================
# VISUALIZATION 2: TRAFFIC IMPACT ANALYSIS
# =============================================================================

print("🎨 Creating Visualization 2: Traffic Impact Analysis...")

fig2 = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'Speed Reduction During Incidents',
        'Vehicle Count During Incidents',
        'Impact Duration by Severity',
        'Real-time Traffic Flow'
    ),
    specs=[
        [{"type": "bar"}, {"type": "bar"}],
        [{"type": "box"}, {"type": "scatter"}]
    ],
    vertical_spacing=0.12
)

# Prepare impact data
impact_alerts = impact_df[impact_df['High_Impact_Accident'] == True]
normal_traffic = impact_df[impact_df['High_Impact_Accident'] == False]

# Subplot 1: Speed Comparison
if not impact_alerts.empty:
    fig2.add_trace(
        go.Bar(
            x=impact_alerts['road_id'],
            y=impact_alerts['avg_current_speed'],
            name='During Incident',
            marker_color='#DC3912',
            text=impact_alerts['avg_current_speed'].round(1),
            textposition='auto',
        ),
        row=1, col=1
    )

if not normal_traffic.empty:
    # Get average normal speeds for comparison
    normal_speeds = normal_traffic.groupby('road_id')['avg_current_speed'].mean().reset_index()
    fig2.add_trace(
        go.Bar(
            x=normal_speeds['road_id'],
            y=normal_speeds['avg_current_speed'],
            name='Normal Traffic',
            marker_color='#109618',
            opacity=0.7
        ),
        row=1, col=1
    )

# Subplot 2: Vehicle Count Comparison
if not impact_alerts.empty:
    fig2.add_trace(
        go.Bar(
            x=impact_alerts['road_id'],
            y=impact_alerts['vehicle_count'],
            name='During Incident',
            marker_color='#FF9900',
            text=impact_alerts['vehicle_count'],
            textposition='auto',
        ),
        row=1, col=2
    )

# Subplot 3: Impact Analysis by Severity
if not impact_alerts.empty and 'severity' in impact_alerts.columns:
    for severity in impact_alerts['severity'].unique():
        severity_data = impact_alerts[impact_alerts['severity'] == severity]
        fig2.add_trace(
            go.Box(
                y=severity_data['avg_current_speed'],
                name=severity,
                boxpoints='all',
                jitter=0.3,
                marker_color={
                    'High': '#DC3912',
                    'Medium': '#FF9900',
                    'Low': '#109618'
                }[severity]
            ),
            row=2, col=1
        )

# Subplot 4: Real-time Traffic Flow
if 'window_start' in impact_df.columns:
    impact_df_sorted = impact_df.sort_values('window_start')

    # Plot lines for each road
    roads = impact_df_sorted['road_id'].unique()[:4]  # Limit to 4 roads for clarity

    for i, road in enumerate(roads):
        road_data = impact_df_sorted[impact_df_sorted['road_id'] == road]
        color = ['#3366CC', '#DC3912', '#FF9900', '#109618'][i % 4]

        fig2.add_trace(
            go.Scatter(
                x=road_data['window_start'],
                y=road_data['avg_current_speed'],
                mode='lines+markers',
                name=f'Road {road}',
                line=dict(color=color, width=2),
                marker=dict(size=6)
            ),
            row=2, col=2
        )

fig2.update_layout(
    title_text="🚨 TRAFFIC IMPACT ANALYSIS",
    height=700,
    showlegend=True,
    template="plotly_white"
)

fig2.add_hline(y=8, line_dash="dash", line_color="red",
              annotation_text="Alert Threshold", row=1, col=1)

fig2.show()

# =============================================================================
# VISUALIZATION 3: REAL-TIME ALERT DASHBOARD
# =============================================================================

print("🎨 Creating Visualization 3: Real-time Alert Dashboard...")

# Create a comprehensive alert dashboard
fig3 = go.Figure()

# Add traffic flow lines
if 'window_start' in impact_df.columns:
    for road in impact_df['road_id'].unique():
        road_data = impact_df[impact_df['road_id'] == road].sort_values('window_start')

        # Determine line style based on impact
        line_style = dict(width=2)
        if road_data['High_Impact_Accident'].any():
            line_style = dict(width=4, dash='dash')

        fig3.add_trace(
            go.Scatter(
                x=road_data['window_start'],
                y=road_data['avg_current_speed'],
                mode='lines+markers',
                name=f'Road {road}',
                line=line_style,
                marker=dict(
                    size=8,
                    color=road_data['vehicle_count'],
                    colorscale='Viridis',
                    showscale=True,
                    colorbar=dict(title="Vehicle Count")
                ),
                hovertemplate=(
                    "<b>Road %{x}</b><br>" +
                    "Speed: %{y:.1f} km/h<br>" +
                    "Vehicles: %{marker.color}<br>" +
                    "Time: %{x}<extra></extra>"
                )
            )
        )

# Add alert thresholds and zones
fig3.add_hrect(y0=0, y1=8, line_width=0, fillcolor="red", opacity=0.2,
              annotation_text="High Impact Zone", annotation_position="left")

fig3.add_hline(y=8, line_dash="dash", line_color="red",
              annotation_text="Alert Threshold (8 km/h)")

fig3.update_layout(
    title="🚦 REAL-TIME TRAFFIC MONITORING DASHBOARD",
    xaxis_title="Time",
    yaxis_title="Average Speed (km/h)",
    height=600,
    template="plotly_dark",
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

fig3.show()

# =============================================================================
# VISUALIZATION 4: SEVERITY HEATMAP
# =============================================================================

print("🎨 Creating Visualization 4: Severity Heatmap...")

# Create a heatmap of impact severity
if not impact_alerts.empty and 'severity' in impact_alerts.columns:
    # Prepare data for heatmap
    heatmap_data = impact_alerts.pivot_table(
        index='road_id',
        columns='severity',
        values='avg_current_speed',
        aggfunc='mean'
    ).fillna(0)

    fig4 = go.Figure(data=go.Heatmap(
        z=heatmap_data.values,
        x=heatmap_data.columns,
        y=heatmap_data.index,
        colorscale='RdYlGn_r',  # Red for low speeds (bad), Green for high speeds (good)
        hoverongaps=False,
        hovertemplate=(
            "Road: %{y}<br>" +
            "Severity: %{x}<br>" +
            "Avg Speed: %{z:.1f} km/h<extra></extra>"
        )
    ))

    fig4.update_layout(
        title="🔥 TRAFFIC IMPACT HEATMAP BY ROAD AND SEVERITY",
        xaxis_title="Accident Severity",
        yaxis_title="Road ID",
        height=400,
        template="plotly_white"
    )

    fig4.show()
else:
    print("⚠ Insufficient data for heatmap visualization")

# =============================================================================
# VISUALIZATION 5: IMPACT RECOVERY TIMELINE
# =============================================================================

print("🎨 Creating Visualization 5: Impact Recovery Timeline...")

# Analyze recovery patterns
if 'window_start' in impact_df.columns and not impact_alerts.empty:

    # Find recovery patterns for each road with incidents
    recovery_data = []

    for road in impact_alerts['road_id'].unique():
        road_data = impact_df[impact_df['road_id'] == road].sort_values('window_start')

        # Find incident windows and subsequent recovery
        incident_windows = road_data[road_data['High_Impact_Accident'] == True]

        for _, incident in incident_windows.iterrows():
            incident_time = incident['window_start']

            # Find recovery data (next 2 windows after incident)
            future_data = road_data[road_data['window_start'] > incident_time].head(2)

            for _, recovery in future_data.iterrows():
                recovery_data.append({
                    'road_id': road,
                    'severity': incident['severity'],
                    'time_from_incident': (recovery['window_start'] - incident_time).total_seconds() / 60,
                    'speed_recovery': recovery['avg_current_speed'],
                    'vehicle_recovery': recovery['vehicle_count']
                })

    if recovery_data:
        recovery_df = pd.DataFrame(recovery_data)

        fig5 = px.scatter(
            recovery_df,
            x='time_from_incident',
            y='speed_recovery',
            color='severity',
            size='vehicle_recovery',
            hover_data=['road_id'],
            title='🔄 TRAFFIC RECOVERY PATTERNS AFTER INCIDENTS',
            labels={
                'time_from_incident': 'Time After Incident (minutes)',
                'speed_recovery': 'Average Speed (km/h)',
                'severity': 'Incident Severity'
            },
            color_discrete_map={
                'High': '#DC3912',
                'Medium': '#FF9900',
                'Low': '#109618'
            }
        )

        fig5.update_layout(
            height=500,
            template="plotly_white"
        )

        fig5.show()

# =============================================================================
# SUMMARY STATISTICS
# =============================================================================

print("\n" + "="*60)
print("📊 ACCIDENT IMPACT ANALYSIS SUMMARY")
print("="*60)

if not impact_alerts.empty:
    total_alerts = len(impact_alerts)
    affected_roads = impact_alerts['road_id'].nunique()
    avg_impact_speed = impact_alerts['avg_current_speed'].mean()
    min_speed = impact_alerts['avg_current_speed'].min()

    print(f"🚨 High Impact Alerts: {total_alerts}")
    print(f"🛣  Roads Affected: {affected_roads}")
    print(f"📉 Average Speed During Incidents: {avg_impact_speed:.1f} km/h")
    print(f"📊 Lowest Recorded Speed: {min_speed:.1f} km/h")

    if 'severity' in impact_alerts.columns:
        severity_summary = impact_alerts['severity'].value_counts()
        print("🚦 Severity Distribution:")
        for severity, count in severity_summary.items():
            print(f"   • {severity}: {count} alerts")

    print(f"📈 Normal Traffic Speed Range: 25-40 km/h")
    print(f"🎯 Alert Threshold: < 8 km/h speed OR < 3 vehicles")
else:
    print("✅ No high impact incidents detected in the data")
    print("📊 Normal traffic conditions maintained")

print("="*60)
print("✅ Dashboard creation completed!")

