"""
Traffic Congestion Analysis
Author: Ishita Parnami 
Date: 21 November 2025
Big Data Project - Jk Lakshmipat University
"""

# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13I-dd7M5szoY3fhGvGRsP-pAlFrnNDZQ
"""

# !pip install pyspark

# !pip install plotly

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, window, avg, desc, to_timestamp
from pyspark.sql.types import StructType, StructField, StringType, DoubleType

# Initialize Spark session
spark = SparkSession.builder \
    .appName("TrafficCongestionAnalysis") \
    .getOrCreate()

# 1. Load road info (static CSV)
road_info = spark.read.option("header", True).csv("road_info.csv") \
    .select("road_id", "speed_limit", "city")

# 2. Load vehicle data from JSON file
schema = StructType([
    StructField("vehicle_id", StringType(), True),
    StructField("road_id", StringType(), True),
    StructField("current_speed", DoubleType(), True),
    StructField("timestamp", StringType(), True)
])

vehicle_data = spark.read.schema(schema).json("live_stream.json")

# Transformation
joined = vehicle_data.join(road_info, on="road_id", how="inner")
joined = joined.withColumn("speed_difference", col("speed_limit").cast("double") - col("current_speed"))
congestion_df = joined.filter(col("speed_difference") > 20)
congestion_df = congestion_df.withColumn("timestamp", to_timestamp("timestamp"))

# Windowed aggregation
windowed = congestion_df.groupBy(
    "road_id", "city", window("timestamp", "5 minutes")
).agg(
    avg("current_speed").alias("avg_current_speed"),
    avg("speed_limit").alias("avg_speed_limit")
)

result_df = windowed.withColumn(
    "congested",
    col("avg_speed_limit") - col("avg_current_speed") > 20
)

# Sort by congestion severity, keep top 5 most congested roads
top5 = result_df.orderBy((col("avg_speed_limit") - col("avg_current_speed")).desc()).limit(5)

# Convert to Pandas for visualization
top5_pd = top5.toPandas()

# Save to CSV for the visualization script
top5_pd.to_csv("congestion_top5.csv", index=False)

print("Top 5 Most Congested Roads:")
top5.show(truncate=False)

# Stop Spark session
spark.stop()

# =============================================================================
# TRAFFIC CONGESTION ANALYSIS WITH DIRECT VISUALIZATION
# =============================================================================

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, window, avg, desc, to_timestamp, when, lit
from pyspark.sql.types import StructType, StructField, StringType, DoubleType
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import pandas as pd

print("🚦 Starting Traffic Congestion Analysis...")

# =============================================================================
# STEP 1: INITIALIZE SPARK SESSION
# =============================================================================

spark = SparkSession.builder \
    .appName("TrafficCongestionAnalysis") \
    .config("spark.sql.adaptive.enabled", "true") \
    .config("spark.sql.adaptive.coalescePartitions.enabled", "true") \
    .getOrCreate()

print("✅ Spark session initialized")

# =============================================================================
# STEP 2: DATA EXTRACTION
# =============================================================================

# Load road information (static data)

road_info = spark.read.option("header", True).csv("road_info.csv") \
    .select("road_id", "speed_limit", "city", "name")


# Load vehicle streaming data from JSON

schema = StructType([
    StructField("vehicle_id", StringType(), True),
    StructField("road_id", StringType(), True),
    StructField("current_speed", DoubleType(), True),
    StructField("timestamp", StringType(), True)
])

vehicle_data = spark.read.schema(schema).json("live_stream.json")

vehicle_data.printSchema()

vehicle_data.show(10, truncate=False)

# =============================================================================
# STEP 3: DATA TRANSFORMATION
# =============================================================================

print("🔄 Processing data transformations...")

# Join vehicle data with road information
joined_data = vehicle_data.join(road_info, on="road_id", how="inner")
print(f"After join: {joined_data.count()} records")

# Calculate speed difference and congestion status
processed_data = joined_data \
    .withColumn("speed_limit_double", col("speed_limit").cast("double")) \
    .withColumn("speed_difference", col("speed_limit_double") - col("current_speed")) \
    .withColumn("is_congested", when(col("speed_difference") > 20, True).otherwise(False)) \
    .withColumn("timestamp_formatted", to_timestamp("timestamp"))

print("Processed Data Sample:")
processed_data.select("road_id", "current_speed", "speed_limit", "speed_difference", "is_congested").show(10)

# Calculate congestion statistics
congestion_stats = processed_data.groupBy("road_id", "city", "name") \
    .agg(
        avg("current_speed").alias("avg_speed"),
        avg("speed_limit_double").alias("avg_speed_limit"),
        avg("speed_difference").alias("avg_speed_diff"),
        avg(when(col("is_congested"), 1).otherwise(0)).alias("congestion_ratio")
    ) \
    .withColumn("congestion_level",
                when(col("avg_speed_diff") > 30, "Severe")
                .when(col("avg_speed_diff") > 20, "High")
                .when(col("avg_speed_diff") > 10, "Moderate")
                .otherwise("Low"))

print("Congestion Statistics:")
congestion_stats.show(truncate=False)

# =============================================================================
# STEP 4: WINDOWED ANALYSIS FOR TOP 5 CONGESTED ROADS
# =============================================================================

print("⏰ Performing windowed analysis...")

# Filter only congested records for windowed analysis
congested_records = processed_data.filter(col("is_congested") == True)
print(f"Congested records: {congested_records.count()}")

# 5-minute windowed aggregation
windowed_analysis = congested_records.groupBy(
    "road_id", "city", "name", window("timestamp_formatted", "5 minutes")
).agg(
    avg("current_speed").alias("avg_current_speed"),
    avg("speed_limit_double").alias("avg_speed_limit"),
    avg("speed_difference").alias("avg_speed_difference"),
    lit("5 min window").alias("analysis_period")
)

# Get top 5 most congested roads
top5_congested = windowed_analysis.orderBy(col("avg_speed_difference").desc()).limit(5)

print("🚨 TOP 5 MOST CONGESTED ROADS:")
top5_congested.show(truncate=False)

# =============================================================================
# STEP 5: CONVERT TO PANDAS FOR VISUALIZATION
# =============================================================================

print("📊 Converting to Pandas for visualization...")

# Convert main datasets to Pandas
congestion_stats_pd = congestion_stats.toPandas()
top5_congested_pd = top5_congested.toPandas()
processed_sample_pd = processed_data.limit(100).toPandas()

print("Pandas DataFrames created:")
print(f"- Congestion stats: {len(congestion_stats_pd)} roads")
print(f"- Top 5 congested: {len(top5_congested_pd)} roads")

# =============================================================================
# STEP 6: CREATE COMPREHENSIVE VISUALIZATIONS (UPDATED)
# =============================================================================

print("🎨 Creating visualizations...")

# Visualization 1: Top 5 Congested Roads - Speed Comparison (Improved)
if not top5_congested_pd.empty:
    fig1 = go.Figure()

    fig1.add_trace(go.Bar(
        name="Avg Current Speed",
        x=top5_congested_pd["name"],
        y=top5_congested_pd["avg_current_speed"],
        text=top5_congested_pd["avg_current_speed"].round(1),
        textposition="inside"
    ))

    fig1.add_trace(go.Bar(
        name="Speed Limit",
        x=top5_congested_pd["name"],
        y=top5_congested_pd["avg_speed_limit"],
        text=top5_congested_pd["avg_speed_limit"].round(1),
        textposition="inside"
    ))

    fig1.update_layout(
        title="🚨 Top 5 Most Congested Roads (Speed Comparison)",
        xaxis_title="Road Name",
        yaxis_title="Speed (km/h)",
        barmode="group",
        template="plotly_white",
        height=550,
    )

    fig1.show()
    print("✅ Visualization 1 updated successfully")



# Visualization 2: Congestion Difference (Bar Chart)
if not top5_congested_pd.empty:
    fig2 = px.bar(
        top5_congested_pd,
        x="name",
        y="avg_speed_difference",
        text="avg_speed_difference",
        title="🔥 Speed Difference for Top 5 Congested Roads",
        labels={"avg_speed_difference": "Speed Difference (km/h)", "name": "Road Name"},
        template="plotly_white"
    )

    fig2.update_traces(textposition="outside")
    fig2.update_layout(height=550)

    fig2.show()
    print("✅ Visualization 2 created: Speed Difference Chart")



# Visualization 3: Congestion Ratio (Bubble Chart)
if not congestion_stats_pd.empty:
    fig3 = px.scatter(
        congestion_stats_pd,
        x="road_id",
        y="avg_speed_diff",
        size="congestion_ratio",
        color="congestion_level",
        hover_name="name",
        title="🟡 Road Congestion Ratio Overview",
        labels={"avg_speed_diff": "Avg Speed Diff (km/h)"},
        template="plotly_white",
    )

    fig3.update_layout(height=550)
    fig3.show()
    print("✅ Visualization 3 created: Congestion Ratio Bubble Chart")



# Visualization 4: Congestion Level Distribution (Pie Chart)
if not congestion_stats_pd.empty:
    level_counts = congestion_stats_pd["congestion_level"].value_counts()

    fig4 = px.pie(
        names=level_counts.index,
        values=level_counts.values,
        title="📊 Congestion Level Distribution",
        template="plotly_white",
        color=level_counts.index,
        color_discrete_map={
            "Severe": "#d62728",
            "High": "#ff7f0e",
            "Moderate": "#fdb462",
            "Low": "#7fc97f",
        }
    )

    fig4.update_traces(textposition="inside", textinfo="percent+label")
    fig4.update_layout(height=550)
    fig4.show()
    print("✅ Visualization 4 updated successfully")

# =============================================================================
# STEP 7: SUMMARY STATISTICS
# =============================================================================

print("\n" + "="*60)
print("📊 TRAFFIC CONGESTION ANALYSIS SUMMARY")
print("="*60)

total_roads = congestion_stats_pd['road_id'].nunique()
total_cities = congestion_stats_pd['city'].nunique()
severe_congestion = len(congestion_stats_pd[congestion_stats_pd['congestion_level'] == 'Severe'])
avg_speed_diff = congestion_stats_pd['avg_speed_diff'].mean()

print(f"• Total Roads Analyzed: {total_roads}")
print(f"• Cities Covered: {total_cities}")
print(f"• Roads with Severe Congestion: {severe_congestion}")
print(f"• Average Speed Difference: {avg_speed_diff:.2f} km/h")
print(f"• Most Congested Road: {top5_congested_pd.iloc[0]['road_id'] if not top5_congested_pd.empty else 'N/A'}")
print(f"• Highest Speed Difference: {top5_congested_pd['avg_speed_difference'].max() if not top5_congested_pd.empty else 0:.2f} km/h")

# =============================================================================
# STEP 8: CLEANUP
# =============================================================================

print("\n🧹 Cleaning up Spark session...")
spark.stop()
print("✅ Analysis completed successfully!")

