"""
Traffic Congestion Analysis
Author: Ishita Parnami 
Date: 21 November 2025
Big Data Project - Jk Lakshmipat University
"""

# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URkbVr9zy9T8Dn0iEBesn4bulTsXvHUW
"""

# =============================================================================
# VEHICLE TYPE ANALYSIS ETL PIPELINE
# =============================================================================

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum as sum_, avg as avg_, expr, count, when, lit, round
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, DateType
import pandas as pd

print("🚗 Starting Vehicle Type Analysis ETL Pipeline...")

# Initialize Spark Session
spark = SparkSession.builder \
    .appName("VehicleTypeAnalysis") \
    .config("spark.sql.adaptive.enabled", "true") \
    .getOrCreate()

# =============================================================================
# STEP 1: EXTRACTION
# =============================================================================

print("📁 Step 1: Data Extraction...")

# Define schema for vehicle count data
vehicle_schema = StructType([
    StructField("road_id", StringType(), True),
    StructField("date", StringType(), True),
    StructField("cars", IntegerType(), True),
    StructField("bikes", IntegerType(), True),
    StructField("trucks", IntegerType(), True)
])

try:
    # Extract vehicle count data
    vehicle_count = spark.read.schema(vehicle_schema).json("vehicle_count.json")
    print("✅ Vehicle count data loaded successfully")
    print(f"Vehicle count records: {vehicle_count.count()}")
    vehicle_count.show(5, truncate=False)

except Exception as e:
    print(f"❌ Error loading vehicle_count.json: {e}")
    print("📋 Generating sample vehicle data...")

    # Generate sample vehicle data
    sample_vehicle_data = [
        ("R001", "2025-11-21", 150, 80, 20),
        ("R002", "2025-11-21", 200, 120, 50),
        ("R003", "2025-11-21", 180, 60, 40),
        ("R004", "2025-11-21", 120, 40, 60),
        ("R005", "2025-11-21", 90, 100, 10),
        ("R006", "2025-11-21", 220, 80, 30),
        ("R007", "2025-11-21", 80, 150, 5),
        ("R008", "2025-11-21", 300, 60, 80),
        ("R009", "2025-11-21", 110, 70, 45),
        ("R010", "2025-11-21", 180, 90, 25),
        ("R001", "2025-11-22", 160, 85, 25),
        ("R002", "2025-11-22", 210, 110, 55),
        ("R003", "2025-11-22", 190, 65, 45),
        ("R004", "2025-11-22", 130, 45, 65),
        ("R005", "2025-11-22", 95, 105, 12)
    ]

    vehicle_count = spark.createDataFrame(sample_vehicle_data, vehicle_schema)
    print("Sample vehicle data created:")
    vehicle_count.show(10, truncate=False)

try:
    # Extract road information
    road_info = spark.read.option("header", True).csv("road_info.csv") \
        .select("road_id", "name", "city", "lanes", "length_km", "speed_limit")
    print("✅ Road info data loaded successfully")
    print(f"Road info records: {road_info.count()}")
    road_info.show(5, truncate=False)

except Exception as e:
    print(f"❌ Error loading road_info.csv: {e}")
    spark.stop()
    exit()

# =============================================================================
# STEP 2: TRANSFORMATION
# =============================================================================

print("\n🔄 Step 2: Data Transformation...")

# Join vehicle data with road information
print("🔗 Joining vehicle data with road information...")
joined = vehicle_count.join(road_info, on="road_id", how="inner")
print(f"After join: {joined.count()} records")

# Calculate totals and percentages with error handling
print("📊 Calculating vehicle statistics...")
joined = joined \
    .withColumn("total_vehicles", col("cars") + col("bikes") + col("trucks")) \
    .withColumn("trucks_percent",
                when(col("total_vehicles") > 0, (col("trucks") / col("total_vehicles")) * 100)
                .otherwise(0)) \
    .withColumn("bikes_percent",
                when(col("total_vehicles") > 0, (col("bikes") / col("total_vehicles")) * 100)
                .otherwise(0)) \
    .withColumn("cars_percent",
                when(col("total_vehicles") > 0, (col("cars") / col("total_vehicles")) * 100)
                .otherwise(0)) \
    .withColumn("lanes", col("lanes").cast("integer"))

# Round percentages for better readability
joined = joined \
    .withColumn("trucks_percent", round(col("trucks_percent"), 2)) \
    .withColumn("bikes_percent", round(col("bikes_percent"), 2)) \
    .withColumn("cars_percent", round(col("cars_percent"), 2))

print("Transformed Data Sample:")
joined.select("road_id", "city", "cars", "bikes", "trucks", "total_vehicles",
              "trucks_percent", "bikes_percent", "cars_percent").show(10, truncate=False)

# =============================================================================
# STEP 3: AGGREGATION
# =============================================================================

print("\n📈 Step 3: Data Aggregation...")

# Aggregate data by road and city
agg = joined.groupBy("road_id", "city", "lanes").agg(
    sum_("cars").alias("total_cars"),
    sum_("bikes").alias("total_bikes"),
    sum_("trucks").alias("total_trucks"),
    sum_("total_vehicles").alias("sum_total_vehicles"),
    count("date").alias("days_observed"),
    avg_("trucks_percent").alias("avg_trucks_percent"),
    avg_("bikes_percent").alias("avg_bikes_percent"),
    avg_("cars_percent").alias("avg_cars_percent"),
    avg_("cars").alias("avg_daily_cars"),
    avg_("bikes").alias("avg_daily_bikes"),
    avg_("trucks").alias("avg_daily_trucks"),
    avg_("total_vehicles").alias("avg_daily_total")
)

# Calculate vehicle density (vehicles per lane per day)
agg = agg.withColumn("vehicle_density",
                     round(col("avg_daily_total") / col("lanes"), 2))

# Round all percentage columns
agg = agg \
    .withColumn("avg_trucks_percent", round(col("avg_trucks_percent"), 2)) \
    .withColumn("avg_bikes_percent", round(col("avg_bikes_percent"), 2)) \
    .withColumn("avg_cars_percent", round(col("avg_cars_percent"), 2))

print("Aggregated Data Sample:")
agg.show(10, truncate=False)

# =============================================================================
# STEP 4: PATTERN IDENTIFICATION
# =============================================================================

print("\n🔍 Step 4: Pattern Identification...")

# Identify different patterns
high_truck_roads = agg.filter(col("avg_trucks_percent") > 30)
high_bike_roads = agg.filter(col("avg_bikes_percent") > 40)
high_car_roads = agg.filter(col("avg_cars_percent") > 60)
overloaded_roads = agg.filter(col("vehicle_density") > 1000)  # Adjust threshold as needed

print(f"🚛 Roads with high truck percentage (>30%): {high_truck_roads.count()}")
if high_truck_roads.count() > 0:
    high_truck_roads.select("road_id", "city", "avg_trucks_percent").show(truncate=False)

print(f"🏍 Roads with high bike usage (>40%): {high_bike_roads.count()}")
if high_bike_roads.count() > 0:
    high_bike_roads.select("road_id", "city", "avg_bikes_percent").show(truncate=False)

print(f"🚗 Roads with high car usage (>60%): {high_car_roads.count()}")
if high_car_roads.count() > 0:
    high_car_roads.select("road_id", "city", "avg_cars_percent").show(truncate=False)

print(f"📊 Overloaded roads (density > 1000): {overloaded_roads.count()}")
if overloaded_roads.count() > 0:
    overloaded_roads.select("road_id", "city", "vehicle_density").show(truncate=False)

# Create comprehensive pattern analysis
pattern_analysis = agg.withColumn("road_type",
    when(col("avg_trucks_percent") > 30, "Truck Route")
    .when(col("avg_bikes_percent") > 40, "Bike Friendly")
    .when(col("avg_cars_percent") > 60, "Car Dominant")
    .when(col("vehicle_density") > 1000, "Overloaded")
    .otherwise("Mixed Usage")
)

print("Road Type Classification:")
pattern_analysis.groupBy("road_type").count().orderBy("count", ascending=False).show(truncate=False)

# =============================================================================
# STEP 5: LOAD
# =============================================================================

print("\n💾 Step 5: Data Loading...")

# Save aggregated data to Parquet
try:
    agg.write.mode("overwrite").parquet("output/vehicle_type_stats")
    print("✅ Aggregated data saved to Parquet")
except Exception as e:
    print(f"❌ Error saving to Parquet: {e}")

# Save pattern analysis for visualization
try:
    pattern_analysis.write.mode("overwrite").parquet("output/road_pattern_analysis")
    print("✅ Pattern analysis saved to Parquet")
except Exception as e:
    print(f"❌ Error saving pattern analysis: {e}")

# Convert to Pandas for CSV output and visualization
agg_pd = agg.toPandas()
pattern_pd = pattern_analysis.toPandas()

# Save to CSV for easy access
agg_pd.to_csv("vehicle_type_analysis.csv", index=False)
pattern_pd.to_csv("road_pattern_analysis.csv", index=False)

print("✅ Data saved to CSV files for visualization")

# =============================================================================
# STEP 6: SUMMARY STATISTICS
# =============================================================================

print("\n" + "="*60)
print("📊 VEHICLE TYPE ANALYSIS SUMMARY")
print("="*60)

total_roads = agg_pd['road_id'].nunique()
total_cities = agg_pd['city'].nunique()
avg_truck_percent = agg_pd['avg_trucks_percent'].mean()
avg_bike_percent = agg_pd['avg_bikes_percent'].mean()
avg_car_percent = agg_pd['avg_cars_percent'].mean()
max_density = agg_pd['vehicle_density'].max()

print(f"🛣  Total Roads Analyzed: {total_roads}")
print(f"🏙  Cities Covered: {total_cities}")
print(f"🚛 Average Truck Percentage: {avg_truck_percent:.1f}%")
print(f"🏍  Average Bike Percentage: {avg_bike_percent:.1f}%")
print(f"🚗 Average Car Percentage: {avg_car_percent:.1f}%")
print(f"📈 Maximum Vehicle Density: {max_density:.0f} vehicles/lane/day")
print(f"📊 Road Type Distribution:")
road_type_counts = pattern_pd['road_type'].value_counts()
for road_type, count in road_type_counts.items():
    print(f"   • {road_type}: {count} roads")

print("="*60)

# Stop Spark session
spark.stop()
print("✅ ETL Pipeline completed successfully!")

# =============================================================================
# VEHICLE TYPE ANALYSIS VISUALIZATIONS
# =============================================================================

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import numpy as np

print("📊 Creating Vehicle Type Analysis Visualizations...")

# Load data
try:
    df = pd.read_csv("vehicle_type_analysis.csv")
    pattern_df = pd.read_csv("road_pattern_analysis.csv")
    print("✅ Data loaded successfully")
    print(f"Records loaded: {len(df)}")
    print("\nData Sample:")
    print(df.head())

except FileNotFoundError:
    print("❌ Data files not found. Please run ps-3.py first")
    exit()

# =============================================================================
# VISUALIZATION 1: VEHICLE TYPE DISTRIBUTION OVERVIEW
# =============================================================================

print("\n🎨 Creating Visualization 1: Vehicle Type Distribution Overview...")

fig1 = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'Vehicle Type Distribution by Road',
        'Average Vehicle Type Proportions',
        'Vehicle Density by City',
        'Road Type Classification'
    ),
    specs=[
        [{"type": "bar"}, {"type": "pie"}],
        [{"type": "bar"}, {"type": "bar"}]
    ],
    vertical_spacing=0.12,
    horizontal_spacing=0.08
)

# Subplot 1: Vehicle type distribution for top 10 roads
top_roads = df.nlargest(10, 'sum_total_vehicles')
fig1.add_trace(
    go.Bar(
        x=top_roads['road_id'],
        y=top_roads['total_cars'],
        name='Cars',
        marker_color='#1f77b4'
    ),
    row=1, col=1
)

fig1.add_trace(
    go.Bar(
        x=top_roads['road_id'],
        y=top_roads['total_bikes'],
        name='Bikes',
        marker_color='#ff7f0e'
    ),
    row=1, col=1
)

fig1.add_trace(
    go.Bar(
        x=top_roads['road_id'],
        y=top_roads['total_trucks'],
        name='Trucks',
        marker_color='#2ca02c'
    ),
    row=1, col=1
)

# Subplot 2: Average vehicle type proportions (Pie chart)
avg_types = df[['avg_cars_percent', 'avg_bikes_percent', 'avg_trucks_percent']].mean()
fig1.add_trace(
    go.Pie(
        labels=['Cars', 'Bikes', 'Trucks'],
        values=[avg_types['avg_cars_percent'], avg_types['avg_bikes_percent'], avg_types['avg_trucks_percent']],
        hole=0.4,
        marker_colors=['#1f77b4', '#ff7f0e', '#2ca02c'],
        name="Vehicle Proportions"
    ),
    row=1, col=2
)

# Subplot 3: Vehicle density by city
city_density = df.groupby('city')['vehicle_density'].mean().sort_values(ascending=False)
fig1.add_trace(
    go.Bar(
        x=city_density.index,
        y=city_density.values,
        marker_color='#d62728',
        name="Vehicle Density"
    ),
    row=2, col=1
)

# Subplot 4: Road type classification
road_type_counts = pattern_df['road_type'].value_counts()
fig1.add_trace(
    go.Bar(
        x=road_type_counts.index,
        y=road_type_counts.values,
        marker_color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'],
        name="Road Types"
    ),
    row=2, col=2
)

fig1.update_layout(
    title_text="🚗 VEHICLE TYPE ANALYSIS OVERVIEW",
    height=700,
    showlegend=True,
    barmode='stack'
)

fig1.show()

# =============================================================================
# VISUALIZATION 2: HIGH TRUCK PERCENTAGE ROADS
# =============================================================================

print("🎨 Creating Visualization 2: High Truck Percentage Analysis...")

high_truck = df[df['avg_trucks_percent'] > 30]

if not high_truck.empty:
    fig2 = make_subplots(
        rows=1, cols=2,
        subplot_titles=(
            'Roads with High Truck Percentage (>30%)',
            'Truck Impact on Total Traffic'
        ),
        specs=[[{"type": "bar"}, {"type": "scatter"}]]
    )

    # Subplot 1: High truck percentage roads
    fig2.add_trace(
        go.Bar(
            x=high_truck['road_id'],
            y=high_truck['avg_trucks_percent'],
            marker_color='#2ca02c',
            name='Truck Percentage',
            text=high_truck['avg_trucks_percent'].round(1),
            textposition='auto',
        ),
        row=1, col=1
    )

    # Subplot 2: Truck impact scatter plot
    fig2.add_trace(
        go.Scatter(
            x=df['avg_trucks_percent'],
            y=df['vehicle_density'],
            mode='markers',
            marker=dict(
                size=df['sum_total_vehicles']/1000,
                color=df['avg_trucks_percent'],
                colorscale='Viridis',
                showscale=True,
                colorbar=dict(title="Truck %")
            ),
            text=df['road_id'],
            hovertemplate=(
                "<b>Road %{text}</b><br>" +
                "Truck %: %{x:.1f}%<br>" +
                "Density: %{y:.0f}<br>" +
                "Total Vehicles: %{marker.size:.0f}K<extra></extra>"
            ),
            name="Truck Impact"
        ),
        row=1, col=2
    )

    fig2.update_layout(
        title_text="🚛 HIGH TRUCK PERCENTAGE ANALYSIS",
        height=500,
        showlegend=False
    )

    fig2.add_hline(y=1000, line_dash="dash", line_color="red",
                  annotation_text="High Density", row=1, col=2)

    fig2.show()
else:
    print("⚠ No roads with high truck percentage found")

# =============================================================================
# VISUALIZATION 3: VEHICLE DENSITY HEATMAP
# =============================================================================

print("🎨 Creating Visualization 3: Vehicle Density Heatmap...")

# Create a pivot table for heatmap
pivot_data = df.pivot_table(
    index='city',
    columns='road_id',
    values='vehicle_density',
    aggfunc='mean'
).fillna(0)

fig3 = go.Figure(data=go.Heatmap(
    z=pivot_data.values,
    x=pivot_data.columns,
    y=pivot_data.index,
    colorscale='Viridis',
    hoverongaps=False,
    hovertemplate=(
        "City: %{y}<br>" +
        "Road: %{x}<br>" +
        "Density: %{z:.0f} vehicles/lane<extra></extra>"
    )
))

fig3.update_layout(
    title="🔥 VEHICLE DENSITY HEATMAP BY CITY AND ROAD",
    xaxis_title="Road ID",
    yaxis_title="City",
    height=500
)

fig3.show()

# =============================================================================
# VISUALIZATION 4: COMPREHENSIVE ROAD ANALYSIS
# =============================================================================

print("🎨 Creating Visualization 4: Comprehensive Road Analysis...")

# Select top 15 roads for detailed analysis
top_roads_detailed = df.nlargest(15, 'sum_total_vehicles')

fig4 = go.Figure()

# Add bars for each vehicle type
fig4.add_trace(go.Bar(
    name='Cars',
    x=top_roads_detailed['road_id'],
    y=top_roads_detailed['total_cars'],
    marker_color='#1f77b4',
    text=top_roads_detailed['avg_cars_percent'].round(1),
    texttemplate='%{text}%',
    textposition='inside'
))

fig4.add_trace(go.Bar(
    name='Bikes',
    x=top_roads_detailed['road_id'],
    y=top_roads_detailed['total_bikes'],
    marker_color='#ff7f0e',
    text=top_roads_detailed['avg_bikes_percent'].round(1),
    texttemplate='%{text}%',
    textposition='inside'
))

fig4.add_trace(go.Bar(
    name='Trucks',
    x=top_roads_detailed['road_id'],
    y=top_roads_detailed['total_trucks'],
    marker_color='#2ca02c',
    text=top_roads_detailed['avg_trucks_percent'].round(1),
    texttemplate='%{text}%',
    textposition='inside'
))

fig4.update_layout(
    title='📊 DETAILED VEHICLE DISTRIBUTION BY ROAD (Top 15)',
    xaxis_title='Road ID',
    yaxis_title='Total Vehicles',
    barmode='stack',
    height=600,
    showlegend=True
)

fig4.show()

# =============================================================================
# VISUALIZATION 5: ROAD PATTERN RADAR CHART
# =============================================================================

print("🎨 Creating Visualization 5: Road Pattern Radar Chart...")

# Create radar chart for different road types
road_types = pattern_df['road_type'].unique()

if len(road_types) > 0:
    fig5 = go.Figure()

    for road_type in road_types[:4]:  # Limit to 4 types for clarity
        type_data = pattern_df[pattern_df['road_type'] == road_type].iloc[0]

        fig5.add_trace(go.Scatterpolar(
            r=[
                type_data['avg_cars_percent'],
                type_data['avg_bikes_percent'],
                type_data['avg_trucks_percent'],
                type_data['vehicle_density'] / 50,  # Scale down for radar
                type_data['sum_total_vehicles'] / 10000  # Scale down
            ],
            theta=['Cars %', 'Bikes %', 'Trucks %', 'Density', 'Total Vehicles'],
            fill='toself',
            name=road_type
        ))

    fig5.update_layout(
        polar=dict(
            radialaxis=dict(
                visible=True,
                range=[0, 100]
            )),
        title="🔄 ROAD TYPE CHARACTERISTICS (Radar Chart)",
        height=500
    )

    fig5.show()

# =============================================================================
# SUMMARY STATISTICS
# =============================================================================

print("\n" + "="*60)
print("📈 VEHICLE TYPE ANALYSIS RESULTS")
print("="*60)

print(f"🚛 High Truck Roads (>30%): {len(df[df['avg_trucks_percent'] > 30])}")
print(f"🏍  High Bike Roads (>40%): {len(df[df['avg_bikes_percent'] > 40])}")
print(f"🚗 High Car Roads (>60%): {len(df[df['avg_cars_percent'] > 60])}")
print(f"📊 Overloaded Roads (density > 1000): {len(df[df['vehicle_density'] > 1000])}")

print(f"\n🏆 Top 5 Roads by Total Vehicles:")
top_5_total = df.nlargest(5, 'sum_total_vehicles')[['road_id', 'city', 'sum_total_vehicles']]
for _, row in top_5_total.iterrows():
    print(f"   • {row['road_id']} ({row['city']}): {row['sum_total_vehicles']:,.0f} vehicles")

print(f"\n📈 Top 5 Roads by Vehicle Density:")
top_5_density = df.nlargest(5, 'vehicle_density')[['road_id', 'city', 'vehicle_density']]
for _, row in top_5_density.iterrows():
    print(f"   • {row['road_id']} ({row['city']}): {row['vehicle_density']:.0f} vehicles/lane")

print("="*60)
print("✅ All visualizations completed successfully!")

